import React from "react";
import { BrowserRouter as Router, Switch, Route } from "react-router-dom";
import BnavBar from "./Footer.js";
import Home from "./Home.js";
import Selection from "./Selection.js";
import Profile from "./Profile.js";
import Admin from "./AdminPanel/Admin";
import Experiences1 from "./Experiences1.js";
import Login from "./Login.js";
import Register from "./Register.js";
import Forget from "./Forget.js";
import AdminRegister from "./AdminRegister";
import ForgotPassword from "./ResetPassword";
import RecoveryPassword from "./RecoveryPassword";
import PrivateRoute from "./PrivateRoute";

function RouteConfig() {
  return (
    <Router>
      <div className="comp">
        <Switch>
          <PrivateRoute
            exact
            path="/register"
            publicValue={true}
            component={Register}
          />
          <PrivateRoute
            exact
            path="/registeradmin"
            publicValue={true}
            component={AdminRegister}
          />
          <PrivateRoute
            exact
            path="/login"
            publicValue={true}
            component={Login}
          />
          <PrivateRoute exact path="/" publicValue={true} component={Login} />
          <PrivateRoute
            exact
            path="/forget"
            publicValue={true}
            component={Forget}
          />
          <PrivateRoute
            exact
            path="/user/resetPassword/:userEmail/reset/:userId"
            publicValue={true}
            component={ForgotPassword}
          />
          <PrivateRoute
            exact
            path="/user/recoveryPassword"
            publicValue={true}
            component={RecoveryPassword}
          />
          <PrivateRoute
            exact
            path="/selection/adventuretrip"
            publicValue={false}
            isAdminProps="false"
            component={Selection}
          />
          <PrivateRoute
            exact
            path="/selection/experiencies"
            publicValue={false}
            isAdminProps="false"
            component={Selection}
          />
          <PrivateRoute
            exact
            path="/selection/senses"
            publicValue={false}
            isAdminProps="false"
            component={Selection}
          />
          <PrivateRoute
            exact
            path="/selection/localfriend"
            publicValue={false}
            isAdminProps="false"
            component={Selection}
          />

          <PrivateRoute
            exact
            path="/experiencies1"
            publicValue={false}
            isAdminProps="false"
            component={Experiences1}
          />
          <PrivateRoute
            exact
            path="/profile"
            publicValue={false}
            isAdminProps="false"
            component={Profile}
          />

          <PrivateRoute
            exact
            path="/profile/information"
            isAdminProps="false"
            publicValue={false}
            component={Profile}
          />
          <PrivateRoute
            exact
            path="/profile/reservations"
            isAdminProps="false"
            publicValue={false}
            component={Profile}
          />
          <PrivateRoute
            exact
            path="/profile/localfriend"
            isAdminProps="false"
            publicValue={false}
            component={Profile}
          />
          <PrivateRoute
            exact
            path="/selection/theweek"
            isAdminProps="false"
            publicValue={false}
            component={Selection}
          />
          <PrivateRoute
            exact
            path="/selection/discovery"
            isAdminProps="false"
            publicValue={false}
            component={Selection}
          />
          <PrivateRoute
            exact
            path="/home"
            isAdminProps="false"
            publicValue={false}
            component={Home}
          />

          <PrivateRoute
            exact
            path="/profile/information/personal"
            component={Profile}
            isAdminProps="false"
            publicValue={false}
          />
          <PrivateRoute
            exact
            path="/profile/information/location"
            component={Profile}
            isAdminProps="false"
            publicValue={false}
          />
          <PrivateRoute
            exact
            path="/profile/information/contact"
            component={Profile}
            isAdminProps="false"
            publicValue={false}
          />
          <PrivateRoute
            exact
            path="/profile/information/payment-methods"
            component={Profile}
            isAdminProps="false"
            publicValue={false}
          />
          <PrivateRoute
            exact
            path="/profile/information/payments"
            component={Profile}
            isAdminProps="false"
            publicValue={false}
          />
          <PrivateRoute
            exact
            path="/profile/reservations/groups"
            component={Profile}
            isAdminProps="false"
            publicValue={false}
          />
          <PrivateRoute
            exact
            path="/profile/reservations/experiences"
            component={Profile}
            isAdminProps="false"
            publicValue={false}
          />

          <PrivateRoute
            exact
            path="/profile/localfriend/data"
            component={Profile}
            isAdminProps="false"
            publicValue={false}
          />
          <PrivateRoute
            exact
            path="/profile/localfriend/detail"
            component={Profile}
            isAdminProps="false"
            publicValue={false}
          />
          <PrivateRoute
            exact
            path="/profile/localfriend/experiences"
            component={Profile}
            isAdminProps="false"
            publicValue={false}
          />
          <PrivateRoute
            exact
            path="/profile/localfriend/reservations"
            component={Profile}
            isAdminProps="false"
            publicValue={false}
          />
          <PrivateRoute
            exact
            path="/selection"
            component={Selection}
            isAdminProps="false"
            publicValue={false}
          />
          <PrivateRoute
            exact
            path="/profile/reservations/groups/details"
            component={Profile}
            isAdminProps="false"
            publicValue={false}
          />
          <PrivateRoute
            exact
            path="/profile/localfriend/experiences/update"
            component={Profile}
            isAdminProps="false"
            publicValue={false}
          />
          <PrivateRoute
            exact
            path="/profile/localfriend/experiences/new"
            component={Profile}
            isAdminProps="false"
            publicValue={false}
          />

          {/* admin panel */}
          <PrivateRoute
            exact
            path="/admin"
            isAdminProps="true"
            publicValue={false}
            component={Admin}
          />
          <PrivateRoute
            exact
            path="/admin/families"
            component={Admin}
            isAdminProps="true"
            publicValue={false}
          />
          <PrivateRoute
            exact
            path="/admin/groups"
            component={Admin}
            isAdminProps="true"
            publicValue={false}
          />
          <PrivateRoute
            exact
            path="/admin/experiences"
            component={Admin}
            isAdminProps="true"
            publicValue={false}
          />
          <PrivateRoute
            exact
            path="/admin/hotels"
            component={Admin}
            isAdminProps="true"
            publicValue={false}
          />
          <PrivateRoute
            exact
            path="/admin/destinations"
            component={Admin}
            isAdminProps="true"
            publicValue={false}
          />
          <PrivateRoute
            exact
            path="/admin/insurances"
            component={Admin}
            isAdminProps="true"
            publicValue={false}
          />
          <PrivateRoute
            exact
            path="/admin/users"
            component={Admin}
            isAdminProps="true"
            publicValue={false}
          />
          <PrivateRoute
            exact
            path="/admin/localfriends"
            component={Admin}
            isAdminProps="true"
            publicValue={false}
          />
          <PrivateRoute
            exact
            path="/admin/reservations"
            component={Admin}
            isAdminProps="true"
            publicValue={false}
          />
          <PrivateRoute
            exact
            path="/admin/payments"
            component={Admin}
            isAdminProps="true"
            publicValue={false}
          />
          <PrivateRoute
            exact
            path="/admin/fees"
            component={Admin}
            isAdminProps="true"
            publicValue={false}
          />

          {/* update */}
          <PrivateRoute
            exact
            path="/admin/families/update"
            component={Admin}
            isAdminProps="true"
            publicValue={false}
          />
          <PrivateRoute
            exact
            path="/admin/hotels/update"
            component={Admin}
            isAdminProps="true"
            publicValue={false}
          />
          <PrivateRoute
            exact
            path="/admin/families/new"
            component={Admin}
            isAdminProps="true"
            publicValue={false}
          />
          <PrivateRoute
            exact
            path="/admin/hotels/new"
            component={Admin}
            isAdminProps="true"
            publicValue={false}
          />
          <PrivateRoute
            exact
            path="/admin/destinations/update"
            component={Admin}
            isAdminProps="true"
            publicValue={false}
          />
          <PrivateRoute
            exact
            path="/admin/destinations/new"
            component={Admin}
            isAdminProps="true"
            publicValue={false}
          />
          <PrivateRoute
            exact
            path="/admin/insurances/update"
            component={Admin}
            isAdminProps="true"
            publicValue={false}
          />
          <PrivateRoute
            exact
            path="/admin/insurances/new"
            component={Admin}
            isAdminProps="true"
            publicValue={false}
          />
          <PrivateRoute
            exact
            path="/admin/users/update"
            component={Admin}
            isAdminProps="true"
            publicValue={false}
          />
          <PrivateRoute
            exact
            path="/admin/users/new"
            component={Admin}
            isAdminProps="true"
            publicValue={false}
          />
          <PrivateRoute
            exact
            path="/admin/groups/update"
            component={Admin}
            isAdminProps="true"
            publicValue={false}
          />
          <PrivateRoute
            exact
            path="/admin/groups/new"
            component={Admin}
            isAdminProps="true"
            publicValue={false}
          />
          <PrivateRoute
            exact
            path="/admin/localfriends/update"
            component={Admin}
            isAdminProps="true"
            publicValue={false}
          />
          <PrivateRoute
            exact
            path="/admin/localfriends/new"
            component={Admin}
            isAdminProps="true"
            publicValue={false}
          />
          <PrivateRoute
            exact
            path="/admin/payments/update"
            component={Admin}
            isAdminProps="true"
            publicValue={false}
          />
          <PrivateRoute
            exact
            path="/admin/fees/new"
            component={Admin}
            isAdminProps="true"
            publicValue={false}
          />
          <PrivateRoute
            exact
            path="/admin/fees/update"
            component={Admin}
            isAdminProps="true"
            publicValue={false}
          />
          <PrivateRoute
            exact
            path="/admin/reservations/update"
            component={Admin}
            isAdminProps="true"
            publicValue={false}
          />
          <PrivateRoute
            exact
            path="/admin/reservations/new"
            component={Admin}
            isAdminProps="true"
            publicValue={false}
          />
          <PrivateRoute
            exact
            path="/admin/experiences/update"
            component={Admin}
            isAdminProps="true"
            publicValue={false}
          />
          <PrivateRoute
            exact
            path="/admin/experiences/new"
            component={Admin}
            isAdminProps="true"
            publicValue={false}
          />
          <Route path="*" component={() => <h2>404 Not Found</h2>} />
        </Switch>
      </div>
      <BnavBar />
    </Router>
  );
}
export default RouteConfig;
